# UNSW-NB15 Cleaning

## Setup

In [1]:
import numpy as np
import pandas as pd
import config
from pathlib import Path

In [15]:
def load_data(root=config.UNSWNB15_ROOT, shuffle_seed=0):
    file_paths = {
        'testing': 'Training and Testing Sets/UNSW_NB15_testing-set.csv',
        'training': 'Training and Testing Sets/UNSW_NB15_training-set.csv',
        'events': 'UNSW-NB15_LIST_EVENTS.csv',
    }
    data = {name: pd.read_csv(root / path) for name, path in file_paths.items()}
    data['features'] = pd.read_csv(root / 'NUSW-NB15_features.csv', encoding='cp1252')
    NB15_parts = [pd.read_csv(root / f'UNSW-NB15_{i}.csv') for i in range(1, 5)]
    for df in NB15_parts:
        df.columns = data['features']['Name']
    
    train_df = pd.concat(NB15_parts, ignore_index=True)
    if shuffle_seed:
        train_df = train_df.sample(frac=1, random_state=shuffle_seed).reset_index(drop=True)
    
    return train_df

train_df = load_data().drop_duplicates()

C:\Users\taznk\AppData\Local\Temp\ipykernel_14808\2670186426.py:10: DtypeWarning: Columns (1,3,47) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(root / f'UNSW-NB15_{i}.csv') for i in range(1, 5)
C:\Users\taznk\AppData\Local\Temp\ipykernel_14808\2670186426.py:10: DtypeWarning: Columns (3,39,47) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(root / f'UNSW-NB15_{i}.csv') for i in range(1, 5)


In [16]:
train_df.head()

Name       srcip  sport          dstip dsport proto state       dur  sbytes  \
0     59.166.0.0  33661  149.171.126.9   1024   udp   CON  0.036133     528   
1     59.166.0.6   1464  149.171.126.7     53   udp   CON  0.001119     146   
2     59.166.0.5   3593  149.171.126.5     53   udp   CON  0.001209     132   
3     59.166.0.3  49664  149.171.126.0     53   udp   CON  0.001169     146   
4     59.166.0.0  32119  149.171.126.9    111   udp   CON  0.078339     568   

Name  dbytes  sttl  ...  ct_ftp_cmd  ct_srv_src  ct_srv_dst ct_dst_ltm  \
0        304    31  ...           0           2           4          2   
1        178    31  ...           0          12           8          1   
2        164    31  ...           0           6           9          1   
3        178    31  ...           0           7           9          1   
4        312    31  ...           0           2           4          2   

Name  ct_src_ ltm  ct_src_dport_ltm  ct_dst_sport_ltm  ct_dst_src_ltm  \
0               3                 1                 1               2   
1               2                 2                 1               1   
2               1                 1                 1               1   
3               1                 1                 1               1   
4               3                 1                 1               2   

Name  attack_cat  Label  
0            NaN      0  
1            NaN      0  
2            NaN      0  
3            NaN      0  
4            NaN      0  

[5 rows x 49 columns]

In [17]:
data['features']

No.              Name      Type   \
0     1             srcip    nominal   
1     2             sport    integer   
2     3             dstip    nominal   
3     4            dsport    integer   
4     5             proto    nominal   
5     6             state    nominal   
6     7               dur      Float   
7     8            sbytes    Integer   
8     9            dbytes    Integer   
9    10              sttl    Integer   
10   11              dttl    Integer   
11   12             sloss    Integer   
12   13             dloss    Integer   
13   14           service    nominal   
14   15             Sload      Float   
15   16             Dload      Float   
16   17             Spkts    integer   
17   18             Dpkts    integer   
18   19              swin    integer   
19   20              dwin    integer   
20   21             stcpb    integer   
21   22             dtcpb    integer   
22   23           smeansz    integer   
23   24           dmeansz    integer   
24   25       trans_depth    integer   
25   26       res_bdy_len    integer   
26   27              Sjit      Float   
27   28              Djit      Float   
28   29             Stime  Timestamp   
29   30             Ltime  Timestamp   
30   31           Sintpkt      Float   
31   32           Dintpkt      Float   
32   33            tcprtt      Float   
33   34            synack      Float   
34   35            ackdat      Float   
35   36   is_sm_ips_ports     Binary   
36   37      ct_state_ttl    Integer   
37   38  ct_flw_http_mthd    Integer   
38   39      is_ftp_login     Binary   
39   40        ct_ftp_cmd    integer   
40   41        ct_srv_src    integer   
41   42        ct_srv_dst    integer   
42   43        ct_dst_ltm    integer   
43   44       ct_src_ ltm    integer   
44   45  ct_src_dport_ltm    integer   
45   46  ct_dst_sport_ltm    integer   
46   47    ct_dst_src_ltm    integer   
47   48        attack_cat    nominal   
48   49             Label     binary   

                                          Description  
0                                   Source IP address  
1                                  Source port number  
2                              Destination IP address  
3                             Destination port number  
4                                Transaction protocol  
5   Indicates to the state and its dependent proto...  
6                               Record total duration  
7            Source to destination transaction bytes   
8             Destination to source transaction bytes  
9           Source to destination time to live value   
10           Destination to source time to live value  
11           Source packets retransmitted or dropped   
12       Destination packets retransmitted or dropped  
13  http, ftp, smtp, ssh, dns, ftp-data ,irc  and ...  
14                             Source bits per second  
15                        Destination bits per second  
16                Source to destination packet count   
17                 Destination to source packet count  
18              Source TCP window advertisement value  
19         Destination TCP window advertisement value  
20                    Source TCP base sequence number  
21               Destination TCP base sequence number  
22  Mean of the ?ow packet size transmitted by the...  
23  Mean of the ?ow packet size transmitted by the...  
24  Represents the pipelined depth into the connec...  
25  Actual uncompressed content size of the data t...  
26                               Source jitter (mSec)  
27                          Destination jitter (mSec)  
28                                  record start time  
29                                   record last time  
30             Source interpacket arrival time (mSec)  
31        Destination interpacket arrival time (mSec)  
32  TCP connection setup round-trip time, the sum ...  
33  TCP connection setup time, the time between th...  
34  TCP connection setup time, the time bet

## Impute NaN

In [18]:
print('NaN entries:')
for c in train_df.columns:
    n_nan = pd.isna(train_df[c]).sum()
    frac = n_nan / len(train_df)
    if n_nan > 0: print(f'{c}: {n_nan} ({frac:.2f})')

NaN entries:
ct_flw_http_mthd: 933603 (0.45)
is_ftp_login: 1014165 (0.49)
attack_cat: 1959771 (0.95)


In [19]:
train_df['attack_cat'].fillna('normal', inplace = True)
train_df['attack_cat'] = train_df['attack_cat'].apply(lambda x: x.strip().lower())
train_df['ct_flw_http_mthd'].fillna(0, inplace=True)
train_df['is_ftp_login'].fillna(0, inplace=True)

pd.isna(train_df).any(axis=1).sum()

C:\Users\taznk\AppData\Local\Temp\ipykernel_14808\4127053838.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_df['attack_cat'].fillna('normal', inplace = True)
C:\Users\taznk\AppData\Local\Temp\ipykernel_14808\4127053838.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.



np.int64(0)

## Unique Values

In [20]:
train_df.describe(include="O")

Name         srcip    sport          dstip   dsport    proto    state  \
count      2059417  2059417        2059417  2059417  2059417  2059417   
unique          43   100343             47   128297      135       16   
top     59.166.0.4        0  149.171.126.3       53      tcp      FIN   
freq        192686    20653         192515   233820  1448858  1433507   

Name    service ct_ftp_cmd attack_cat  
count   2059417    2059417    2059417  
unique       13         13         11  
top           -                normal  
freq    1169180    1014165    1959771

In [21]:
categorical = ('srcip',	'sport',	'dstip',	'dsport',	'proto',	'state',	'service',	'ct_ftp_cmd',	'attack_cat')
for c in categorical:
    print('\n' + c)
    u = train_df[c].unique()
    print(len(u))
    print(u)


srcip
43
['59.166.0.0' '59.166.0.6' '59.166.0.5' '59.166.0.3' '10.40.182.3'
 '59.166.0.7' '10.40.170.2' '59.166.0.1' '59.166.0.2' '59.166.0.4'
 '175.45.176.3' '175.45.176.2' '175.45.176.0' '59.166.0.8' '59.166.0.9'
 '175.45.176.1' '10.40.182.1' '10.40.85.1' '192.168.241.243' '10.40.85.30'
 '149.171.126.16' '149.171.126.2' '149.171.126.11' '149.171.126.4'
 '149.171.126.5' '149.171.126.17' '149.171.126.19' '149.171.126.9'
 '149.171.126.8' '149.171.126.7' '149.171.126.15' '149.171.126.6'
 '149.171.126.0' '149.171.126.1' '149.171.126.3' '149.171.126.13'
 '149.171.126.12' '149.171.126.10' '149.171.126.18' '127.0.0.1'
 '149.171.126.14' '10.40.85.10' '10.40.182.6']

sport
100343
[33661 1464 3593 ... 533 933 706]

dstip
47
['149.171.126.9' '149.171.126.7' '149.171.126.5' '149.171.126.0'
 '149.171.126.4' '10.40.182.3' '149.171.126.6' '10.40.170.2'
 '149.171.126.18' '149.171.126.16' '149.171.126.8' '149.171.126.2'
 '149.171.126.1' '149.171.126.10' '149.171.126.3' '149.171.126.15'
 '149.171.126.

In [22]:
train_df['ct_ftp_cmd'] = train_df['ct_ftp_cmd'].astype('str')
train_df['ct_ftp_cmd'] = train_df['ct_ftp_cmd'].replace(' ', '0')
train_df['ct_ftp_cmd'] = train_df['ct_ftp_cmd'].astype('int')
train_df['ct_ftp_cmd'].unique()

array([0, 1, 6, 2, 4, 8, 5, 3])

In [23]:
train_df['is_ftp_login'] = (train_df['is_ftp_login'] > 0).astype(int)
train_df.is_ftp_login.unique()

array([0, 1])

In [24]:
train_df['sport'] = train_df['sport'].astype('str')
train_df['sport'] = pd.to_numeric(train_df['sport'], errors='coerce').fillna(0).astype(int)

train_df['dsport'] = train_df['dsport'].astype('str')
train_df['dsport'] = pd.to_numeric(train_df['dsport'], errors='coerce').fillna(0).astype(int)

train_df.sport.unique(), train_df.dsport.unique()

(array([33661,  1464,  3593, ...,   533,   933,   706]),
 array([1024,   53,  111, ...,  632,  186,  518]))

## Outliers

In [28]:
# TODO
pass

In [30]:
train_df.to_csv(config.INTERM_DIR / 'full_unsw_cleaned.csv', index=False)